export type CardData = {
    text: string,
    size?: number
}

export const needs: CardData[][] = [
    [{text:'Jistota, Bezpečí'}, {text:'Stabilita'}],
    [{text:'Dotek'}, {text:'projevení náklonnosti'}],
    [{text:'Integrita'}, {text:'soulad mezi tím co říkám,'}, {text:'a co dělám', size: 3}],
    [{text:'Klid'}, {text:'možnost dělat věci svým tempem'}, {text:'Klid v duši', size: 3}],
    [{text:'Láska'}],
    [{text:'Dobrodružství'}, {text:'Výzva'}],
    [{text:'Důvěra'}, {text:'Důvěřovat, spolehnout se', size: 2}, {text:'mít něčí důvěru'}],
    [{text:'Jasnost'}, {text:'mít jasno, orientovat se', size: 2}, {text:'vyznat se v tom', size: 2}],
    [{text:'Harmonie'}, {text:'Soulad, Krása'}],
    [{text:'Autonomie'}, {text:'Nezávislost, samostatnost'}, {text:'Vliv na věci, které se mě týkají, možnost volby'}],
    [{text:'Odpočinek'}, {text:'Relaxace'}],
    [{text:'Být podporován'}, {text:'podpora, pomoc'}],
    [{text:'Pořádek'}, {text:'čistota, uspořádanost'}],
    [{text:'Ocenění, uznání'}, {text:'pozornost, být viděn'}],
    [{text:'Dávání, Přispění'}, {text:'Obohacování života druhých'}, {text:'svým konáním', size: 3}],
    [{text:'Být pochopen'}, {text:'být slyšen, být vnímán', size: 2}, {text:'empatie', size: 2}],
    [{text:'Pohyb'}],
    [{text:'Rozumět, Chápat'}, {text:'Vědět, být informován'}],
    [{text:'Přátelství'}, {text:'Blízkost'}],
    [{text:'Progres'}, {text:'Efektivita'}],
    [{text:'Prostor'}, {text:'Prostornost ve fyzickém prostoru'}, {text:'v čase, v konverzaci', size: 3}],
    [{text:'Respekt'}, {text:'být brán vážně', size: 2}, {text:'pocit \"na mě záleží\"', size: 2}],
    [{text:'Sdílení'}],
    [{text:'Moc, vliv'}, {text:'Vliv na věci, které se mě týkají'}],
    [{text:'Soustředění'}],
    [{text:'Řád'}, {text:'Předvídatelnost'}],
    [{text:'Růst rozvoj'}, {text:'učení se'}],
    [{text:'Erós'}, {text:'Sexuální prožívání'}],
    [{text:'Smysl'}, {text:'smysluplnost, významnost, hloubka'}],
    [{text:'Sounáležitost'}, {text:'být s lidmi, nebýt sám'}, {text:'být součástí party, někam patřit'}],
    [{text:'Spolupráce'}, {text:'pracovat na věci společně'}, {text:'společně dosahovat výsledků'}],
    [{text:'Férovost'}, {text:'Přiměřenost', size: 2}, {text:'Vzájemnost', size: 2}],
    [{text:'Přijetí'}, {text:'Být přijímán takový jaký jsem'}],
    [{text:'Zábava'}, {text:'humor'}],
    [{text:'Volnost'}, {text:'Svoboda, Lehkost'}],
    [{text:'Spontánnost'}, {text:'Autentičnost'}],
    [{text:'Transparentnost'}, {text:'Otevřenost', size: 2}, {text:'Přímost (nechodit kolem horké kaše)'}],
    [{text:'Požitek'}, {text:'potěšení smyslů'}],
    [{text:'Intimita'}, {text:'blízkost, hloubka sdíleného prožívání'}],
    [{text:'Hra'}, {text:'hravost, soutěžení'}],
    [{text:'Kompetence'}, {text:'Mistrovství', size: 2}, {text:'ovládnutí dovednosti', size: 3}],
    [{text:'Pozornost'}, {text:'Být slyšen, Být viděn'}],
    [{text:'Zdravi, Svěžest'}, {text:'tělesná, duševní'}, {text:'býtí ve své plné síle'}],
    [{text:'Přesah'}, {text:'Spiritualita, Transcendence'}, {text:'kontakt s něčím, co nás přesahuje'}],
    [{text:'Tvořivost'}, {text:'Sebevyjádření'}],
];

export const feelings: CardData[][] = [
    [{text:'Vztek, Hněv'}, {text:'Naštvání, Zloba', size: 2}],
    [{text:'Netrpělivost'}],
    [{text:'Smutek'}],
    [{text:'Strach'}],
    [{text:'Bezmoc'}],
    [{text:'Rozladění'}, {text:'Podráždění, Rozhořčení', size: 2}],
    [{text:'Napětí'}],
    [{text:'Lítost'}, {text:'Zklamání'}],
    [{text:'Únava'}, {text:'Vyčerpání', size: 2}],
    [{text:'Bolest'}, {text:'Zranění', size: 2}],
    [{text:'Zmatek'}, {text:'Bezradnost', size: 2}],
    [{text:'Rozpaky'}, {text:'Stud', size: 2}],
    [{text:'Zahlcení'}],
    [{text:'Osamělost'}],
    [{text:'Mrzutost'}, {text:'Frustrace'}],
    [{text:'Nervozita'}, {text:'Nuda'}],
    [{text:'Hořkost'}],
    [{text:'Otupělost'}, {text:'Netečnost, odpojení', size: 2}, {text:'rezignace', size: 2}],
    [{text:'Úzkost'}, {text:'Obavy, Beznaděj', size: 2}],
    [{text:'Vděčnost'}, {text:'Naplnění', size: 2}],
    [{text:'Energie'}, {text:'osvěžení', size: 2}],
    [{text:'Klid'}],
    [{text:'Volnost'}, {text:'Bezstarostnost', size: 2}],
    [{text:'Překvapení'}],
    [{text:'Inspirace'}, {text:'Fascinace, Okouzlení', size: 2}],
    [{text:'Radost'}, {text:'štěstí, veselost', size: 2}, {text:'potěšení', size: 2}],
    [{text:'Vyrovnanost'}, {text:'Rovnováha, Sebejistota', size: 2}],
    [{text:'Tíživý pocit'}, {text:'stísněnost', size: 2}],
    [{text:'Zvědavost'}, {text:'Zájem', size: 2}],
    [{text:'Něha'}],
    [{text:'Hrdost'}],
    [{text:'Dobrá nálada'}, {text:'Hřejivý pocit', size: 2}],
    [{text:'Nadšení'}, {text:'Vášeň', size: 2}],
    [{text:'Znechucení'}],
    [{text:'Pohoda'}, {text:'Spokojenost'}],
    [{text:'Povzbuzení'}, {text:'Odhodlání'}],
    [{text:'Pobavení'}, {text:'Rozpustilost', size: 2}],
    [{text:'Naděje'}]
];
